name: 'pubnub'
version: 0.1.1
description: A simple PubNub wrapper in Dart.
author: Sebastian Nozzi
homepage: https://github.com/sebnozzi/pubnub-dart

dependencies:
  browser: '>=0.10.0 <0.11.0'
  js: ^0.6.0
