name: 'pubnub'
version: 0.1.1
description: A simple PubNub wrapper in Dart.
author: Sebastian Nozzi
homepage: https://github.com/sebnozzi/pubnub-dart

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  browser: '>=0.10.0 <0.11.0'
  js: ^0.6.0
